export const MARKETPLACE_CATEGORY_TREE: Record<string, string[]> = {
  "Women's Clothing": [
    "Outerwear & Jackets",
    "Blazers",
    "Wool & Blend",
    "Women's Padded Jackets",
    "Woman Trench",
    "Basic Jacket",
    "Leather & Suede",
    "Real Fur",
    "Couple&Parent-Child Clothing",
    "Couple&Parent-Child Sweatshirts",
    "Couple&Parent-Child Short-Sleeves",
    "Couple&Parent-Child Jackets",
    "Couple&Parent-Child Tops",
    "Couple&Parent-Child Suits",
    "Couple&Parent-Child Pants",
    "Accessories",
    "Scarves & Wraps",
    "Face Masks",
    "Belts & Cummerbunds",
    "Woman Gloves & Mittens",
    "Woman Socks",
    "Woman Hats & Caps",
    "Bottoms",
    "Leggings",
    "Skirts",
    "Woman Jeans",
    "Woman Shorts",
    "Pants & Capris",
    "Wide Leg Pants",
    "Tops & Sets",
    "Ladies Short Sleeve",
    "Women's Camis",
    "Women's Vests",
    "Women's Short-Sleeved Shirts",
    "Women's Long-Sleeved Shirts",
    "Blouses & Shirts",
    "Woman Hoodies & Sweatshirts",
    "Jumpsuits",
    "Rompers",
    "Lady Dresses",
    "Sweaters",
    "Suits & Sets",
    "Weddings & Events",
    "Cocktail Dresses",
    "Evening Dresses",
    "Bridesmaid Dresses",
    "Prom Dresses",
    "Wedding Dresses",
    "Flower Girl Dresses",
  ],
  "Pet Supplies": [
    "Pet Outdoor Supplies",
    "Barking Control Equipments",
    "Trainers",
    "Dog Training Pads & Diapers",
    "Pet Snacks",
    "Pet Bags",
    "Pet Seat Belts",
    "Pet Car Mats",
    "Pet Guardrails",
    "Pet Furnitures",
    "Cat Scratching Posts",
    "Pet Furniture Protectors",
    "Cat Trees & Condos",
    "Pet Furniture Tools",
    "Pet Houses & Cages",
    "Dog Stairs & Steps",
    "Pet Tents",
    "Pet Hammocks",
    "Pet Drinking & Feeding",
    "Pet Bowls",
    "Pet Drinking Tools",
    "Pet Feeding Tools",
    "Fish & Aquatic Pets",
    "Fish Tanks",
    "Fish Tank Decorations",
    "Fish Tank Cleaning Supplies",
    "Pet Collars, Harnesses & Accessories",
    "Pet Hair Accessories",
    "Pet Bows & Ties",
    "Pet Necklaces",
    "Pet Headwears",
    "Pet Glasses",
    "Pet Collars",
    "Pet Leashes",
    "Pet Harnesses",
    "Pet Muzzles",
    "Pet Collar, Leash & Harness Sets",
    "Custom Pet tags, Collars, Leashes & Harnesses",
    "Pet Toys",
    "Pet Chase Toys",
    "Pet Chew Toys",
    "Pet Training and Educational Toys",
    "Pet Sound Toys",
    "Pet Tunnel Toys",
    "Pet Toy Set",
    "Pet Plush Toys",
    "Pet Bedding",
    "Pet Mats",
    "Pet Nests",
    "Pet Beds",
    "Pet Blankets & Quilts",
    "Pet Apparels",
    "Pet Dresses",
    "Pet Tops",
    "Pet Sweaters",
    "Pet Sweatshirts & Hoodies",
    "Pet Coats & Jackets",
    "Pet Jumpsuits",
    "Pet Pajamas",
    "Pet Clothings",
    "Pet Functional Clothings",
    "Pet Clothing Sets",
    "Pet Down & Parkas",
    "Pet Shoes & Socks",
    "Pet Scarves",
    "Bird Supplies",
    "Bird Feeders",
    "Bird Cages",
    "Bird Swings",
    "Bird Toys",
    "Bird Travel Bags",
    "Bird Accessories",
    "Pet Groomings",
    "Pet Hair Removers & Combs",
    "Pet Nail Polishers",
    "Pet Shower Products",
    "Pet Towels",
  ],
  "Home, Garden & Furniture": [
    "Arts, Crafts & Sewing",
    "Decor Paintings",
    "Lace",
    "Apparel Sewing & Fabric",
    "Cross-Stitch",
    "Ribbons",
    "Diamond Painting Cross Stitch",
    "Fabric",
    "Festive & Party Supplies",
    "Christmas Decoration Supplies",
    "Invitation Cards",
    "Cake Decorating Supplies",
    "Decorative Flowers & Wreaths",
    "Party Masks",
    "Event & Party Supplies",
    "Home Textiles",
    "Curtains",
    "Floor Mats",
    "Cushion Covers",
    "Towels",
    "Comforters",
    "Bedding Sets",
    "Pillows",
    "Kitchen, Dining & Bar",
    "Dinnerware",
    "Kitchen Knives & Accessories",
    "Bakeware",
    "Barware",
    "Drinkware",
    "Cooking Tools",
    "Home Storage",
    "Stationeries",
    "Furniture",
    "Storage Bags & Cases & Boxes",
    "First Aid Supplies",
    "Kitchen Storage",
    "Home Office Storage",
    "Clothing & Wardrobe Storage",
    "Bathroom Storage",
    "Storage Bottles & Jars",
    "Musical Instruments",
    "Guitars",
    "Violins",
    "Steel Tongue Drum",
  ],
  "Health, Beauty & Hair": [
    "Makeup",
    "Eyebrow Pencil",
    "Makeup Set",
    "Eyeshadow",
    "Makeup Brushes",
    "Lipstick",
    "False Eyelashes",
    "Wigs & Extensions",
    "Human Hair Wigs",
    "Synthetic Hair Pieces",
    "Synthetic Lace Wigs",
    "Human Hair Lace Wigs",
    "Hair Braids",
    "Synthetic Wigs",
    "Synthetic Hair",
    "Cosplay Wigs",
    "Skin Care",
    "Razor",
    "Face Masks",
    "Sun Care",
    "Essential Oil",
    "Body Care",
    "Facial Care",
    "Beauty Tools",
    "Mirrors",
    "Straightening Irons",
    "Electric Face Cleanser",
    "Face Skin Care Tools",
    "Curling Iron",
    "Facial Steamer",
    "Food & Health",
    "Health Care Products",
    "Nail Art & Tools",
    "Nail Glitters",
    "Stickers & Decals",
    "Nail Decorations",
    "Nail Gel",
    "Nail Dryers",
    "Nail Art Kits",
    "Hair Weaves",
    "Pre-Colored One Pack",
    "Hair Weaving",
    "Hair Styling",
    "Salon Bundle Hair",
    "Pre-Colored Hair Weave",
    "Hair & Accessories",
    "Headband & Hair Band & Hairpin",
    "Human Hair",
  ],
  "Jewelry & Watches": [
    "Women's Watches",
    "Watch Accessories",
    "Women Sports Watches",
    "Dress Watches",
    "Creative Watches",
    "Lovers' Watches",
    "Women's Bracelet Watches",
    "Children's Watches",
    "Men's Watches",
    "Quartz Watches",
    "Mechanical Watches",
    "Digital Watches",
    "Dual Display Watches",
    "Men Sports Watches",
    "Fine Jewelry",
    "Various Gemstones",
    "925 Silver Jewelry",
    "K-Gold",
    "Pearls Jewelry",
    "Fine Earrings",
    "Men's Fine Jewelry",
    "Fine Jewelry Sets",
    "Wedding & Engagement",
    "Bridal Jewelry Sets",
    "Wedding Hair Jewelry",
    "Engagement Rings",
    "Fashion Jewelry",
    "Bracelets & Bangles",
    "Brooches",
    "Keychains",
    "Pocket Watches",
    "Anklets",
    "Charms",
    "Rings",
    "Body Jewelry",
    "Fashion Jewelry Sets",
    "Necklace & Pendants",
    "Men's Cuff Links",
    "Earrings",
  ],
  "Men's Clothing": [
    "Accessories",
    "Socks",
    "Men's Ties",
    "Scarves",
    "Man Gloves & Mittens",
    "Skullies & Beanies",
    "Belts",
    "Bottoms",
    "Pajama Sets",
    "Man Shorts",
    "Cargo Pants",
    "Man Jeans",
    "Harem Pants",
    "Casual Pants",
    "Sweatpants",
    "Underwear & Loungewear",
    "Men's Sleep & Lounge",
    "Shorts",
    "Briefs",
    "Robes",
    "Man Pajama Sets",
    "Boxers",
    "Long Johns",
    "T-Shirts",
    "Geometric",
    "Men's Long-Sleeved",
    "Striped",
    "Solid",
    "3D",
    "Print",
    "Outerwear & Jackets",
    "Suits & Blazer",
    "Men's Sweaters",
    "Genuine Leather",
    "Man Trench",
    "Men's Shirts",
    "Men's Jackets",
    "Men's Suits",
    "Man Hoodies & Sweatshirts",
    "Wool & Blends",
    "Parkas",
    "Down Jackets",
    "Hats & Caps",
    "Baseball Caps",
    "Bomber Hats",
    "Berets",
    "Fedoras",
  ],
  "Women's Shoes": [
    "Woman Boots",
    "Vulcanize Shoes",
    "Women's Insoles",
    "Pumps",
    "Woman Slippers",
    "Woman Sandals",
    "Flats",
    "Heels",
    "Wedges",
    "Running Shoes",
    "Dance Shoes",
    "Hiking Shoes",
  ],
  "Men's Shoes": [
    "Man Boots",
    "Formal Shoes",
    "Men's Insoles",
    "Man Slippers",
    "Vulcanize Shoe",
    "Man Sandals",
    "Casual Shoes",
    "Sneakers",
    "Running Shoes",
    "Skateboarding Shoes",
    "Hiking Shoes",
    "Soccer Shoes",
    "Basketball Shoes",
  ],
  "Camping Equipment": [
    "Camping & Hiking",
    "Tents",
    "Sleeping Bags",
    "Camping Stoves",
    "Camping Furniture",
    "Hiking Backpacks",
    "Hiking Jackets",
    "Outdoor Lanterns",
    "Camping Cookware",
    "Sleeping Pads",
    "Camping Mats",
  ],
  Agriculture: [
    "Farm Tools",
    "Seeds & Seedlings",
    "Fertilizers",
    "Irrigation Equipment",
    "Livestock Supplies",
    "Poultry Supplies",
    "Greenhouse Supplies",
    "Tractors & Farm Machinery",
    "Crop Protection",
    "Harvesting Tools",
  ],
  "Bags & Shoes": [
    "Men's Luggage & Bags",
    "Briefcases",
    "Waist Bags",
    "Girls Bags",
    "Men's Backpacks",
    "Luggage & Travel Bags",
    "Crossbody Bags",
    "Man Wallets",
    "Women's Luggage & Bags",
    "Woman Wallets",
    "Women's Crossbody Bags",
    "Bag Accessories",
    "Evening Bags",
    "Fashion Backpacks",
    "Shoulder Bags",
    "Totes",
    "Boys Bags",
    "Clutches",
  ],
  "Toys, Kids & Babies": [
    "Boys Clothing",
    "Boy Jeans",
    "Boy T-Shirts",
    "Boy Hoodies & Sweatshirts",
    "Outerwear & Coats",
    "Boy Clothing Sets",
    "Boy Accessories",
    "Baby Clothing",
    "Baby Clothing Sets",
    "Baby Rompers",
    "Baby Accessories",
    "Baby Outerwear",
    "Baby Dresses",
    "Baby Pants",
    "Shoes & Bags",
    "Children's Shoes",
    "Boys Shoes",
    "School Bags",
    "Kids Wallets",
    "Girls Shoes",
    "Baby's First Walkers",
    "Toys & Hobbies",
    "Electronic Pets",
    "Blocks",
    "RC Helicopters",
    "Stuffed & Plush Animals",
    "Action & Toy Figures",
    "Girls Clothing",
    "Girls Underwear",
    "Girls' Pants",
    "Family Matching Outfits",
    "Sleepwear & Robes",
    "Tops & Tees",
    "Girl Clothing Sets",
    "Girl Accessories",
    "Girl Dresses",
    "Baby & Mother",
    "Nappy Changing",
    "Activity & Gear",
    "Backpacks & Carriers",
    "Baby Care",
    "Maternity",
  ],
  "Sports & Outdoors": [
    "Other Sports Equipment",
    "Musical Instruments",
    "Hunting",
    "Skiing & Snowboarding",
    "Fitness & Bodybuilding",
    "Golf",
    "Swimming",
    "One-Piece Suits",
    "Bikini Sets",
    "Two-Piece Suits",
    "Men's Swimwear",
    "Cover-Ups",
    "Children's Swimwear",
    "Sneakers",
    "Running Shoes",
    "Dance Shoes",
    "Skateboarding Shoes",
    "Soccer Shoes",
    "Basketball Shoes",
    "Sportswear",
    "Jerseys",
    "Sports Accessories",
    "Outdoor Shorts",
    "Sports Bags",
    "Pants",
    "Cycling",
    "Bicycle Lights",
    "Scooters",
    "Cycling Gloves",
    "Bicycle Helmets",
    "Bicycle Frames",
    "Cycling Jerseys",
    "Bicycles",
    "Fishing",
    "Fishing Reels",
    "Rod Combos",
    "Fishing Tackle Boxes",
    "Fishing Lures",
    "Fishing Rods",
    "Fishing Lines",
  ],
  "Consumer Electronics": [
    "Smart Electronics",
    "Wearable Devices",
    "Smart Home Appliances",
    "Smart Wearable Accessories",
    "Smart Wristbands",
    "Smart Watches",
    "Smart Remote Controls",
    "Camera & Photo",
    "Photo Studio",
    "Camera Drones",
    "Camera & Photo Accessories",
    "Digital Cameras",
    "Action Cameras",
    "Camcorders",
    "Accessories & Parts",
    "Digital Cables",
    "Home Electronic Accessories",
    "Audio & Video Cables",
    "Charger",
    "Batteries",
    "Digital Gear Bags",
    "Video Games",
    "Gamepads",
    "Handheld Game Players",
    "Video Game Consoles",
    "Stickers",
    "Joysticks",
    "Home Audio & Video",
    "Projectors",
    "Television",
    "TV Receivers",
    "Audio Amplifiers",
    "Projectors & Acessories",
    "TV Sticks",
    "Portable Audio & Video",
    "Microphones",
    "Speakers",
    "Earphones & Headphones",
    "VR & AR Devices",
    "MP3 Players",
  ],
  "Home Improvement": [
    "Outdoor Lighting",
    "Flashlights & Torches",
    "Floodlights",
    "Underwater Lights",
    "String Lights",
    "Solar Lamps",
    "Home Appliances",
    "Personal Care Appliances",
    "Cleaning Appliances",
    "Air Conditioning Appliances",
    "Home Appliance Parts",
    "Kitchen Appliances",
    "Indoor Lighting",
    "Chandeliers",
    "Pendant Lights",
    "Downlights",
    "Night Lights",
    "Wall Lamps",
    "Ceiling Lights",
    "LED Lighting",
    "LED Spotlights",
    "Tools",
    "Home Improvement Materials",
    "Measurement & Analysis",
    "Welding & Soldering Supplies",
    "Welding Equipment",
    "Hand Tools",
    "Tool Sets",
    "Tools Storage",
    "Machine Tools & Accessories",
    "Power Tools",
    "Woodworking Machinery",
    "Garden Tools",
  ],
  "Automobiles & Motorcycles": [
    "Interior Accessories",
    "Floor Mats",
    "Car Aromatherapy",
    "Car Perfume",
    "Key Case for Car",
    "Steering Covers",
    "Automobiles Seat Covers",
    "Stowing Tidying",
    "Motorcycle Accessories & Parts",
    "Lighting",
    "Exhaust & Exhaust Systems",
    "Motor Brake System",
    "Motorcycle Seat Covers",
    "Other Motorcycle Accessories",
    "Helmet Headset",
    "Body & Frame",
    "Auto Replacement Parts",
    "Interior Parts",
    "Car Brake System",
    "Spark Plugs & Ignition System",
    "Automobiles Sensors",
    "Exterior Parts",
    "Other Replacement Parts",
    "Car Lights",
    "Windscreen Wipers & Windows",
    "Tools, Maintenance & Care",
    "Car Washer",
    "Diagnostic Tools",
    "Paint Care",
    "Other Maintenance Products",
    "Car Electronics",
    "Vehicle Camera",
    "DVR & Dash Camera",
    "Car Monitors",
    "Vehicle GPS",
    "Car Mirror Video",
    "Car Radios",
    "GPS Trackers",
    "Car Multimedia Player",
    "Alarm Systems & Security",
    "Jump Starter",
    "Exterior Accessories",
    "Car Stickers",
    "Other Exterior Accessories",
    "Car Covers",
  ],
  "Phones & Accessories": [
    "Mobile Phone Parts",
    "SIM Card & Tools",
    "Mobile Batteries",
    "Housings",
    "LCDs",
    "Flex Cables",
    "Touch Panel",
    "Mobile Phones",
    "Quad Core",
    "Single SIM Card",
    "Dual SIM Card",
    "3GB RAM",
    "Octa Core",
    "5-inch Display",
    "Mobile Phone Accessories",
    "Cables",
    "Power Bank",
    "Screen Protectors",
    "Lenses",
    "Holders & Stands",
    "Chargers",
    "Cases & Covers",
    "Huawei Cases",
    "Patterned Cases",
    "Cases For iPhone 6 & 6 Plus",
    "Wallet Cases",
    "Cases For iPhone 7 & 7 Plus",
    "Galaxy S8 Cases",
    "IPhone X Cases",
    "Galaxy S7 Cases",
    "Cases For iPhone 8 & 8 Plus",
    "Xiaomi Cases",
    "Silicone Cases",
    "Flip Cases",
    "Waterptoof Cases",
    "Leather Cases",
  ],
  "Computer & Office": [
    "Storage Devices",
    "SSD",
    "USB Flash Drives",
    "HDD Enclosures",
    "Memory Cards",
    "External Hard Drives",
    "Tablet & Laptop Accessories",
    "Tablet LCD Screens",
    "Laptop Batteries",
    "Laptop Bags & Cases",
    "Tablet Cases",
    "Tablet Accessories",
    "Security & Protection",
    "Alarm & Sensor",
    "Fire Protection",
    "Workplace Safety Supplies",
    "Door Intercom",
    "Surveillance Products",
    "Laptop & Tablets",
    "Phone Call Tablets",
    "2 in 1 Tablets",
    "Laptops",
    "Tablets",
    "Gaming Laptops",
    "Office Electronics",
    "Office & School Supplies",
    "Computer Tablet Accessories",
    "Printer Supplies",
    "3D Printers",
    "3D Pens",
    "Printers",
    "Scanners",
    "Networking",
    "Modem-Router Combos",
    "Wireless Routers",
    "Networking Tools",
    "3G Modems",
    "Network Cable",
  ],
  "Food & Restaurant": ["Kota / Bunny Chow", "Extras", "Meals"],
};

export const MARKETPLACE_TOP_CATEGORIES = Object.keys(MARKETPLACE_CATEGORY_TREE);

export function categoriesForTop(topCategory: string): string[] {
  const subs = MARKETPLACE_CATEGORY_TREE[topCategory] ?? [];
  return [topCategory, ...subs];
}

function escapeRegex(v: string): string {
  return v.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function containsTerm(text: string, term: string): boolean {
  const needle = String(term || "").trim().toLowerCase();
  if (!needle) return false;
  if (/^[a-z0-9]+(?:['-][a-z0-9]+)*$/i.test(needle)) {
    return new RegExp(`\\b${escapeRegex(needle)}\\b`, "i").test(text);
  }
  return text.includes(needle);
}

const TOP_CATEGORY_KEYWORDS: Record<string, string[]> = {
  "Women's Clothing": ["women", "woman", "lady", "ladies", "female", "dress", "blouse", "skirt", "leggings", "jumpsuit", "wedding"],
  "Pet Supplies": ["pet", "dog", "cat", "bird", "fish", "aquatic", "harness", "leash", "groom"],
  "Home, Garden & Furniture": ["home", "garden", "furniture", "kitchen", "bedding", "curtain", "storage", "dining"],
  "Health, Beauty & Hair": ["beauty", "makeup", "skin", "hair", "wig", "nail", "cosmetic", "facial"],
  "Jewelry & Watches": ["jewelry", "watch", "ring", "earring", "necklace", "bracelet", "pendant"],
  "Men's Clothing": ["men", "mens", "man's", "male", "gentlemen", "gents", "boy", "boys"],
  "Bags & Shoes": ["bag", "backpack", "wallet", "luggage", "handbag", "tote", "clutch"],
  "Women's Shoes": ["women", "woman", "lady", "female", "pump", "heel", "ballet", "wedge", "sandal", "slipper", "flat"],
  "Men's Shoes": ["men", "mens", "man", "male", "formal shoe", "loafer", "oxford", "sneaker", "boot", "sandal", "slipper"],
  "Camping Equipment": ["camp", "camping", "tent", "hiking", "backpack", "lantern", "sleeping bag", "outdoor cooking"],
  Agriculture: ["agriculture", "farm", "farming", "tractor", "seed", "fertilizer", "livestock", "crop", "irrigation", "poultry"],
  "Toys, Kids & Babies": ["toy", "baby", "kids", "child", "children", "maternity", "plush", "school bag"],
  "Sports & Outdoors": ["sport", "outdoor", "fitness", "swim", "cycling", "fishing", "jersey", "soccer", "football", "golf"],
  "Consumer Electronics": ["electronics", "camera", "audio", "video", "smart", "headphone", "speaker", "game"],
  "Home Improvement": ["lighting", "tool", "appliance", "welding", "power tool", "ceiling", "lamp", "garden tool"],
  "Automobiles & Motorcycles": ["car", "auto", "motor", "motorcycle", "vehicle", "dash", "gps", "seat cover"],
  "Phones & Accessories": ["phone", "mobile", "charger", "case", "screen protector", "sim", "iphone", "galaxy"],
  "Computer & Office": ["computer", "laptop", "tablet", "office", "printer", "scanner", "router", "ssd"],
  "Food & Restaurant": ["food", "restaurant", "kota", "bunny", "burger", "chips", "meal", "atchaar"],
};

export function keywordsForTop(topCategory: string): string[] {
  return TOP_CATEGORY_KEYWORDS[topCategory] ?? [];
}

export function productMatchesTopCategory(
  product: { title?: string; description?: string; categories?: unknown[]; tags?: unknown[] },
  topCategory: string
): boolean {
  const inferred = inferTopCategory(product);
  if (inferred) return inferred === topCategory;

  const values = [
    String(product.title || ""),
    String(product.description || ""),
    ...(Array.isArray(product.categories) ? product.categories.map((v) => String(v || "")) : []),
    ...(Array.isArray(product.tags) ? product.tags.map((v) => String(v || "")) : []),
  ].join(" ").toLowerCase();
  if (!values.trim()) return false;
  const byCategory = categoriesForTop(topCategory).some((c) => containsTerm(values, c));
  if (byCategory) return true;
  return keywordsForTop(topCategory).some((k) => containsTerm(values, k));
}

export function inferTopCategory(product: {
  title?: string;
  description?: string;
  categories?: unknown[];
  tags?: unknown[];
}): string | null {
  const values = [
    String(product.title || ""),
    String(product.description || ""),
    ...(Array.isArray(product.categories) ? product.categories.map((v) => String(v || "")) : []),
    ...(Array.isArray(product.tags) ? product.tags.map((v) => String(v || "")) : []),
  ].join(" ").toLowerCase();
  if (!values.trim()) return null;

  let best: { name: string; score: number } | null = null;
  for (const top of MARKETPLACE_TOP_CATEGORIES) {
    const exactHits = categoriesForTop(top).reduce((acc, c) => (containsTerm(values, c) ? acc + 2 : acc), 0);
    const keywordHits = keywordsForTop(top).reduce((acc, k) => (containsTerm(values, k) ? acc + 1 : acc), 0);
    let score = exactHits + keywordHits;
    if (top === "Women's Clothing" && /\b(men|man)\b/i.test(values)) score -= 3;
    if (top === "Men's Clothing" && /\b(women|woman|lady|girls)\b/i.test(values)) score -= 3;
    if (top === "Women's Shoes" && /\b(men|man|boy|boys)\b/i.test(values)) score -= 3;
    if (top === "Men's Shoes" && /\b(women|woman|lady|girls)\b/i.test(values)) score -= 3;
    if (!best || score > best.score) best = { name: top, score };
  }
  if (!best || best.score < 1) return null;
  return best.name;
}
