/** Infer gender from SA / Sesotho / common first names for avatar assignment. */
export type InferredGender = "male" | "female";

const FEMALE = new Set(
  [
    "julia",
    "puleng",
    "modiehi",
    "thabile",
    "noqhinyane",
    "olga",
    "tsoakae",
    "monica",
    "ennie",
    "evelyn",
    "hilda",
    "martha",
    "agnes",
    "dorothy",
    "suzan",
    "susan",
    "thobeka",
    "betty",
    "emily",
    "lieketseng",
    "nkanyene",
    "matankiso",
    "evodia",
    "dipuo",
    "anna",
    "refiloe",
    "maria",
    "mantoa",
    "mmatebello",
    "dimakatso",
    "moselantja",
    "khabonina",
    "mapai",
    "matieho",
    "mantwa",
    "pulane",
    "leentse",
    "mphakiseng",
    "morwesi",
    "mamello",
    "patience",
    "grace",
    "rosinah",
    "ida",
    "sannah",
    "albentina",
    "roselina",
    "puseletso",
    "qinisile",
    "joyce",
    "minah",
    "meriam",
    "adeline",
    "elisa",
    "jeannett",
    "annah",
    "fumane",
  ].map((s) => s.toLowerCase())
);

const MALE = new Set(
  [
    "peter",
    "makgabane",
    "lebohang",
    "andries",
    "brand",
    "ben",
    "thabo",
    "abel",
    "ephraim",
    "daniel",
    "samuel",
    "sello",
    "zibele",
    "philemon",
    "mpho",
    "elias",
    "piet",
    "gosiame",
    "anthony",
    "sipho",
    "edgar",
    "kago",
    "michael",
    "phillip",
    "martyens",
    "pule",
    "tshepang",
    "molatlhwa",
    "mxolisi",
    "pitso",
    "austoker",
    "obakeng",
    "thabiso",
    "paul",
    "motsamai",
    "thabang",
    "mdhanwe",
    "ramotete",
    "mafojane",
    "mahlomola",
    "monyane",
    "chabaku",
    "mbuiswa",
    "mosiea",
    "motete",
    "motsienyane",
    "mokadi",
    "motaung",
    "molefe",
    "mofokeng",
    "mosae",
    "maya",
    "ndalane",
    "hlanjwa",
    "kheswa",
    "mngwevu",
    "masangani",
    "khoele",
    "moloi",
    "hlalele",
    "magome",
    "dlamini",
    "chaka",
    "mefi",
    "nongwenye",
    "mbongwe",
    "hlahane",
    "lesiya",
    "mokhina",
    "komme",
    "nkoala",
    "nhlapo",
    "bodibe",
    "skhosana",
    "nale",
    "mokoena",
    "tsohane",
    "leotlela",
    "sandamela",
    "seme",
    "teleko",
    "makume",
    "maseki",
    "zwane",
    "maine",
    "nqobeni",
    "mkhi",
    "mosoeu",
    "radebe",
    "moletsane",
    "loikaneng",
    "sandi",
    "phooko",
    "mmakomane",
    "hlongwane",
    "sebusi",
    "maredi",
    "legkowana",
    "simela",
    "ralekholela",
    "khaba",
    "motsoeneng",
    "kibi",
    "tshabalala",
  ].map((s) => s.toLowerCase())
);

export function inferUserGender(givenNameRaw: string, surnameRaw = ""): InferredGender {
  const norm = (s: string) =>
    String(s || "")
      .toLowerCase()
      .replace(/[^a-z\s]/g, " ")
      .split(/\s+/)
      .filter(Boolean);
  const given = norm(givenNameRaw);
  const surname = norm(surnameRaw);

  let femaleScore = 0;
  let maleScore = 0;
  const scoreTokens = (tokens: string[], weight: number) => {
    for (const t of tokens) {
      if (FEMALE.has(t)) femaleScore += weight;
      if (MALE.has(t)) maleScore += weight;
    }
  };
  scoreTokens(given, 3);
  scoreTokens(surname, 1);

  if (femaleScore > maleScore) return "female";
  if (maleScore > femaleScore) return "male";
  return "male";
}
